### PR TITLE
NSNotificationCenter.addObserver(forName:object:queue:using:) on Linu…

### PR DESCRIPTION
**Pull request by maksimorlovich**
…x Swift >4.0

### CODE REVIEW

**Comment by maksimorlovich** [comment]
@mxcl Could you please review and merge this change in? It fixes PMKFoundation on Linux Swift >4.0 where this routine was renamed from

    NSNotificationCenter.addObserver(forName:object:queue:usingBlock:)
to

    NSNotificationCenter.addObserver(forName:object:queue:using:)

I'm using this framework in a Swift app on Linux using Swift 4.1.2 and it fails to build :( I verified this fix with Swift version 3.1.1, 4.0, 4.0.2, 4.0.3, 4.1, and 4.1.2 and everything builds.

Would you be able to release version 3.1.x with this fix please? Thanks!

**Comment by mxcl** [comment]
We have Swift 4 on Linux in our Travis Matrix. Maybe it’s broken? I created PR #13 in case of that, but it passed.

So either this fix is for Swift 4.1, or our Travis is not testing Swift 4 properly. Any idea which?

**Comment by maksimorlovich** [comment]
Hi @mxcl. I created a matrix of pass/fail results based on v3.1.0, top of tree support-swiftpm-4, and this PR.
pmkfoundation

Looks like something happens when swiftLanguageVersions is added as per the matrix. This PR addresses all the issues and now all permutations of Swift Version + Package.swift tools version build :) Thanks!

**Comment by mxcl** [comment]
3.1.1 tagged. Thanks!

**Pull request merged**
